language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
          env: VENVBIN=/home/travis/virtualenv/bin
        - os: linux
          sudo: required
          python: 3.5
          env: VENVBIN=/home/travis/virtualenv/bin
        - os: linux
          sudo: required
          python: 3.6
          env: VENVBIN=/home/travis/virtualenv/bin
        - os: linux
          sudo: required
          python: 2.7
          env: VENVBIN=/home/travis/virtualenv/bin
        - os: osx
          language: generic
          env: PYENV=2
        - os: osx
          language: generic
          env: PYENV=3
before_install:
  - .travis/before_install.sh
install:
  - python${PYENV} setup.py install
script:
  - env
  - sudo -i ${VENVBIN}/nosetests --with-coverage test/test_partner.py
  - nosetests --with-coverage test/test_server.py
  - nosetests --with-coverage test/test_client.py
  - nosetests --with-coverage test/test_util.py
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aacaa796672a51d47850
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: FVgr37xYK0D1Hfag0KVJlsc5m4x1hf+T2vBLAKZWPCYNq2jEIzCGtMLNGmgHBVqydWHM3HkTJTYqlPyguxC/DYnmLSNL4L6YeG1EUWQ4Zgn/IqK55lb0Sns2Qn4moTN/q53Z6vMUMRS4frnycZLa3AETGAedv5qyR92r7yEzAJk=
  on:
    tags: true
