matrix:
  include:
    - os: linux
      env: TARGET=ubuntu1804
      services: [docker]
      sudo: true
    - os: linux
      env: TARGET=ubuntu2004
      services: [docker]
      sudo: true
    - os: linux
      env: TARGET=mypy
      services: [docker]
      sudo: true
    - os: linux
      env: TARGET=pycodestyle
      services: [docker]
      sudo: true
    - os: linux
      env: TARGET=doc
      services: [docker]
      sudo: true
    - os: osx
      osx_image: xcode12


before_install:
  - .travis/before_install.sh

install:
  - .travis/install.sh

script:
  - .travis/script.sh

deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: FVgr37xYK0D1Hfag0KVJlsc5m4x1hf+T2vBLAKZWPCYNq2jEIzCGtMLNGmgHBVqydWHM3HkTJTYqlPyguxC/DYnmLSNL4L6YeG1EUWQ4Zgn/IqK55lb0Sns2Qn4moTN/q53Z6vMUMRS4frnycZLa3AETGAedv5qyR92r7yEzAJk=
  on:
    tags: true
